### ISSUE TITLE
[Beginner Question]: How to add Vae

### ISSUE THREAD

**Issue by seniorghser** [camenduru/stable-diffusion-webui-colab#200]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### Are you using the latest version of the colab notebook?

- [X] Yes, i am using the latest version from the repo

### Which colab notebook did you use?

any model

### Which repo branch did the colab you use comes from ?

I don't know

### Which tunnel did you use ?

--googleusercontent

### What happened?

i just dont know how to add vae model into colab

**Comment by etherealxx** [comment]
what vae model do you wan't. tell me. i can help you

**Comment by seniorghser** [comment]
it is about the model named AbyssOrangeMix3 (AOM3)

**Comment by machiavel23** [comment]
If you "don't know" the branch, then it's probably the main branch. It also means you can't read before clicking everywhere when you arrivé on a webpage, shame on you.

That said, when a model have its own vae, it's automatically downloaded along the model. For AOM3, here are the download lines:
`!aria2c --console-log-level=error -c -x 16 -s 16 -k 1M https://huggingface.co/WarriorMama777/OrangeMixs/resolve/main/Models/AbyssOrangeMix3/AOM3.safetensors -d /content/stable-diffusion-webui/models/Stable-diffusion -o AOM3.safetensors
!aria2c --console-log-level=error -c -x 16 -s 16 -k 1M https://huggingface.co/WarriorMama777/OrangeMixs/resolve/main/Models/AbyssOrangeMix3/AOM3A1.safetensors -d /content/stable-diffusion-webui/models/Stable-diffusion -o AOM3A1.safetensors
!aria2c --console-log-level=error -c -x 16 -s 16 -k 1M https://huggingface.co/WarriorMama777/OrangeMixs/resolve/main/Models/AbyssOrangeMix3/AOM3A2.safetensors -d /content/stable-diffusion-webui/models/Stable-diffusion -o AOM3A2.safetensors
!aria2c --console-log-level=error -c -x 16 -s 16 -k 1M https://huggingface.co/WarriorMama777/OrangeMixs/resolve/main/Models/AbyssOrangeMix3/AOM3A3.safetensors -d /content/stable-diffusion-webui/models/Stable-diffusion -o AOM3A3.safetensors
!aria2c --console-log-level=error -c -x 16 -s 16 -k 1M https://huggingface.co/WarriorMama777/OrangeMixs/resolve/main/VAEs/orangemix.vae.pt -d /content/stable-diffusion-webui/models/Stable-diffusion -o orangemix.vae.pt`

Which means, when you use the Abyss Orange Mix 3 colab, you have:
> Abyss Orange Mix 3 model
> Abyss Orange Mix 3 A1 model
> Abyss Orange Mix 3 A2 model
> Abyss Orange Mix 3 A3 model
> Orange Mix vae.

So you HAVE the VAE, and it's automatically activated because it's in the same folder than the models.
