### ISSUE TITLE
Question about sd 1.5              

### ISSUE THREAD

**Issue by xMikami** [camenduru/stable-diffusion-webui-colab#318]
Hi, is there only 2.1 collab ? Not 1.5 ? i see the runwayml/sd1.5 but cant figure how to use a model like AO3 with that collab. if so, where i can find a collab like this but for sd 1.5 ? thanks in advance.

**Comment by camenduru** [comment]
Hi @xMikami 👋 we have 
![image](https://user-images.githubusercontent.com/54370274/227747976-6b9140b6-d297-43e8-8e00-54b3ec602bbe.png)

**Comment by xMikami** [comment]
Hi, and yea but i mean a collab that has sd 1.5 base, and with that use a ckpt like AO3. If am not wrong, these collabs has all sd 2.1 base

**Comment by xMikami** [comment]
The question is because I have seen they say the majority of Loras work better in sd 1.5

**Comment by etherealxx** [comment]
@xMikami there's a confusion here. Other than colab that Camenduru shows on that picture (the one with v2 and v2_1 in it), all colab use 1.4/1.5 base.

**Comment by xMikami** [comment]
@etherealxx Oh, so all collabs use 1.5 ? for example the collab with abyssorangemix2 ? i figured they used v2.1 because in one line of the collabs it says "!git clone -b v2.1"

**Comment by xMikami** [comment]
if i use the berry mix 1.5 model and i add a model to it like AO3 Is it still sd v1.5 although I changed the model that comes in the collab?

**Comment by etherealxx** [comment]
@xMikami there's a misconception here.

> !git clone -b v2.1

you know about fork right? so Camenduru (owner of this colab repo) forked auto1111's webui, in order to make sure the webui is stable (the original repo sometimes add bugs when they add features). The way camenduru names the branch of the fork is with versioning, like v1.6, v1.7, etc. The one used for `lite` is branch v1.9, `stable` is v2.0, and `nightly` is v2.1. It has nothing to do with stable diffusion model. It's just coincidences.

> Oh, so all collabs use 1.5 ? for example the collab with abyssorangemix2

yes.

> if i use the berry mix 1.5 collab and i add a model to it like AO3 Is it still sd v1.5

yes.

**Comment by xMikami** [comment]
Very thanks, I was in a mess for weeks, and i understand all now c: .
