### ISSUE TITLE
[bUG] A tensor with all naNs was produced in VAE ... --no-half-vae

### ISSUE THREAD

**Issue by Indras91** [camenduru/stable-diffusion-webui-colab#337]
### What happened?

How to fix error"
modules.device.NansException: A tensor with all naNs was produced in VAE. This could be because there's not enough precision to represent the picture. Try adding - - no-half-vae commandline argument to fix this........ "

### Which repo branch did the colab you use comes from ?

stable

### Which tunnel did you use ?

--cloudflared

### What browsers do you use to access the WebUI ?

Mozilla Firefox

**Comment by basedholychad** [comment]
this error only happen if i using highres upscale and set upscale more than 1,85



NansException: A tensor with all NaNs was produced in Unet. This could be either because there's not enough precision to represent the picture, or because your video card does not support half type. Try setting the "Upcast cross attention layer to float32" option in Settings > Stable Diffusion or using the --no-half commandline argument to fix this. Use --disable-nan-check commandline argument to disable this check.
Time taken: 47.47sTorch active/reserved: 10933/11422 MiB, Sys VRAM: 11597/15102 MiB (76.79%)




it's may not because of model because i've try 5-6 different models
i think it's because today update google or python or colab or whoever they nerfed GPU ram maybe (lol xD) because yesterday i was able to upscale up to 2,85 but today if i set more than 1,85 the error happens

**Comment by camenduru** [comment]
@basedholychad  are you using nightly or stable version

**Comment by basedholychad** [comment]
i'm using nightly version refslave v2  and i also download serveral models from civit each time using batchlinks but all models have same error when using highres

**Comment by camenduru** [comment]
ok thanks ❤ I will test with stable and nightly

**Comment by camenduru** [comment]
@basedholychad please send your png info I am not getting the error

**Comment by basedholychad** [comment]
i think i figured it
if i using the stable version it's still ok
it only error when using nightly version
maybe it's from either from these 3 lines from code 
!sed -i -e '''/    prepare_environment()/a\    os.system\(f\"""sed -i -e ''\"s/dict()))/dict())).cuda()/g\"'' /content/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/util.py""")''' /content/stable-diffusion-webui/launch.py
!sed -i -e 's/fastapi==0.90.1/fastapi==0.89.1/g' /content/stable-diffusion-webui/requirements_versions.txt

!mkdir /content/stable-diffusion-webui/extensions/deforum-for-automatic1111-webui/models

the nightly version lack these 3 lines maybe
or maybe from these 2 lines?
nightly:
!pip install -q torch==2.0.0+cu118 torchvision==0.15.1+cu118 torchaudio==2.0.1+cu118 torchtext==0.15.1 torchdata==0.6.0 --extra-index-url https://download.pytorch.org/whl/cu118 -U
!pip install -q xformers==0.0.18 triton==2.0.0 -U

stable:
!pip install torch==1.13.1+cu116 torchvision==0.14.1+cu116 torchaudio==0.13.1 torchtext==0.14.1 torchdata==0.5.1 --extra-index-url https://download.pytorch.org/whl/cu116 -U
!pip install -q xformers==0.0.16 triton==2.0.0 -U

**Comment by camenduru** [comment]
@basedholychad could you please provide me with the last part of your PNG info like
`Steps: 22, Sampler: DPM++ 2M Karras, CFG scale: 7, Seed: 3152632744, Size: 384x512, Model hash: 7e9a9b674e, Denoising strength: 0.7, Clip skip: 2, ENSD: 31337, Hires upscale: 2, Hires upscaler: Latent`

**Comment by camenduru** [comment]
🥳 @basedholychad how did you solve it

**Comment by basedholychad** [comment]
notice that the nightly missing these 3 lines in the code idk if that's the problems

**Comment by camenduru** [comment]
the problem is `torch==2.0.0+cu118` using more vram than `torch==1.13.1+cu116`

**Comment by Indras91** [comment]
Im used orangemix3 model, the error sometimes come and sometime not, the side effect is the image result is not showing,

**Comment by camenduru** [comment]
This is not a bug. Unfortunately, this is a `torch==2.0.0+cu118` behavior. Please use low numbers on `Upscale by`, like `1.9`, or use the `stable` version

**Comment by etherealxx** [comment]
@camenduru does using `--no-half-vae` on those torch 2 scenario fix the problem too?

**Comment by camenduru** [comment]
@etherealxx not working 😭
