### ISSUE TITLE
Everytime I start run sd I need to install torch and something,it takes some time.Is there any tricks to avoid this?

### ISSUE THREAD

**Issue by MinardWu** [camenduru/stable-diffusion-webui-colab#445]
### What happened?

Everytime I start run sd I need to install torch and something,it takes some time.Is there any tricks to avoid this?

### Colab cell output

```shell
Everytime I start run sd I need to install torch and something,it takes some time.Is there any tricks to avoid this?
```

### Which colab and model(s) were you using when the error occurred?

Everytime I start run sd I need to install torch and something,it takes some time.Is there any tricks to avoid this?

### Which Public WebUI Colab URL were you using when the error occurred?

remote.moe

**Comment by etherealxx** [comment]
if you just refer to the installing torch process: it's because the recent (last month) changes of google colab updated the torch, but stable-diffusion-webui runs on a specific version of it, so the download and installing process is the one slowing it down. (torch is huge, about 2/3 Gb, though colab's internet is fast, it still takes time)

if you refer to the overall 'waiting 8 min before the actual thing starts': it's downloading dependencies used for the entire webui thing. 

If you don't want to wait, you can use the [google drive version here by camenduru himself](https://github.com/camenduru/stable-diffusion-webui-colab/tree/drive) to basically install the entire stable-diffusion-webui on your google drive, so the next time you open it, it will be way faster.

Or use some [community made colabs](https://github.com/camenduru/stable-diffusion-webui-colab/tree/community) like NoCrypt's or Cagliostro, they use pre-compiled dependencies, it's fast, probably 3-4 minute faster.

**Comment by MinardWu** [comment]
Ok, thanks.
