### ISSUE TITLE
where did i go wrong?

### ISSUE THREAD

**Issue by tranthai2k2** [camenduru/stable-diffusion-webui-colab#61]
!wget https://huggingface.co/YoungMasterFromSect/Trauter_LoRAs/resolve/main/LoRA/Misc.%20Characters/Aponia/Aponia_Softpruned.safetensors -O /content/stable-diffusion-webui/extensions/sd-webui-additional-networks/models/LoRA/Aponia_Softpruned.safetensors
it was not in the directory when the site link appeared

**Comment by camenduru** [comment]
Hi @tranthai2k2 👋 please try `lora` instead of `LoRA`  I added the lora folder

`!wget https://huggingface.co/YoungMasterFromSect/Trauter_LoRAs/resolve/main/LoRA/Misc.%20Characters/Aponia/Aponia_Softpruned.safetensors -O /content/stable-diffusion-webui/extensions/sd-webui-additional-networks/models/lora/Aponia_Softpruned.safetensors`

**Comment by camenduru** [comment]
Little note: In Linux, `lora` is a different folder than `LoRA` but in Windows, both are the same folder.

**Comment by tranthai2k2** [comment]
this is not an error maybe it's my computer or my settings or the network
sometimes it works very smoothly
the problem is like this when there is a personal link to the stable for some reason, it takes a long time to load on the website, until I can access the website, it takes a long time to create a picture. For example, a girl I wait 5-6 minutes and when i load png's info it takes about 3 minutes
@camenduru if you have a solution please help me

**Comment by camenduru** [comment]
Hi @tranthai2k2 👋 please test with new version
