### ISSUE TITLE
[New Feature] Colab Run Command 

### ISSUE THREAD

**Issue by camenduru** [camenduru/stable-diffusion-webui-colab#79]
Now we can run commands without restarting the colab 🎉

![Screenshot 2023-02-04 154822](https://user-images.githubusercontent.com/54370274/216769046-0aa250e1-1c69-4ffa-b558-b8bb5ac6b0e6.jpg)

**Comment by yesyeahvh123** [comment]
@camenduru Thanks for the hard work, this saves a lot of time

**Comment by etherealxx** [comment]
i'm thinking about... you can put all the models on this repo into a dropdown list and a clickable download button, instead of different colab link per model. That would save you a lot of time. (It's a bit 'harder' for beginner to figure things out, but you can tell the 'how to' on the github readme page.

**Comment by camenduru** [comment]
Hi @etherealxx 👋 I am working on this https://aica.pages.dev

**Comment by camenduru** [comment]
@etherealxx maybe we can create a colab for advanced users as you suggested

**Comment by yesyeahvh123** [comment]
Some of my thoughts on it
- a bit slow when entering Huggingface tabs
- I don't know the running process, the remaining of the time...it only shows the results when it's done, good if it shows the same process as in Colab console

**Comment by yesyeahvh123** [comment]
@camenduru Some of my thoughts on it

- a bit slow when entering Huggingface tabs (because it shows all the results when process done)
- I don't know the running process, the remaining of the time...it only shows the results when it's done, good if it shows the same process as in Colab console, or show process in Colab console

I think you should create a wider input field to enter multiple lines and show the process running in the Colab console instead of displaying them in the Huggingface extension

**Comment by Scraft161** [comment]
> @etherealxx maybe we can create a colab for advanced users as you suggested

I've personally been working on a colab based on the anything-V4 one which includes various models and LoRAs which you can download before starting SD, it is still something I'm working on and ideally we'd have something in the webui or in the colab where you can just select the models/LoRA you want and then start up SD.

[you can check out the notebook here if you are interested.](https://colab.research.google.com/drive/1rvhWEFwxCLfWTYldg8AsysK4Yx3oqKGI)

**Comment by etherealxx** [comment]
> I've personally been working on a colab...

well, [about that...](https://colab.research.google.com/github/etherealxx/etherportal-webui-colab/blob/master/etherportal.ipynb)😅

Though, i like your approach to some interesting LoRAs and explaining it, and your beginner friendly approach is also a plus.

> we'd have something ... in the colab where you can just select the models/LoRA

Civitai extension is available for that. There are also another good approach for Embedding repo like [Umi-AI](https://github.com/Klokinator/Umi-AI).

**Comment by yatharthk691** [comment]
Sir can you please make one for this  model 
https://civitai.com/models/4488/classic-negative-sd-21-768px

**Comment by etherealxx** [comment]
@Scraft161 now you can post yours [here](https://github.com/camenduru/stable-diffusion-webui-colab/issues/94) i think.

**Comment by camenduru** [comment]
Hi @yatharthk691 👋 please use `sd-civitai-browser` extension

**Comment by camenduru** [comment]
Hi @Scraft161 👋  little example images are so cool 🔥 do you want to add in [community ](https://github.com/camenduru/stable-diffusion-webui-colab/tree/community) branch if you want please push inside your name folder 

![Screenshot 2023-02-13 121804](https://user-images.githubusercontent.com/54370274/218418944-585c0180-5176-4546-80fb-23c52f5c732a.jpg)
